name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashfiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro
      
      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python scripts/promote_model.py
      
      - name: Run Flask app tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest tests/test_flask_app.py 
      
      - name: Login to AWS ECR
        if: success()
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 957417441966.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        if: success()
        run: |
          docker build -t sourav_ecr .

      - name: Tag Docker image
        if: success()
        run: |
          docker tag sourav_ecr:latest 957417441966.dkr.ecr.eu-north-1.amazonaws.com/sourav_ecr:latest

      - name: Push Docker image to AWS ECR
        if: success()
        run: |
          docker push 957417441966.dkr.ecr.eu-north-1.amazonaws.com/sourav_ecr:latest

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws configure set aws access key id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws secret access key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region eu-north-1
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin
            957417441966.dkr.ecr.eu-north-1.amazonaws.com

            docker pull 957417441966.dkr.ecr.eu-north-1.amazonaws.com/sourav_ecr:latest
            docker stop my-app | | true
            docker rm my-app || true
            docker run -d -p 80:5000 -e DAGSHUB_PAT=${ { secrets.DAGSHUB PAT }} -- name hunter-app 
            957417441966.dkr.ecr.eu-north-1.amazonaws.com/sourav_ecr:latest
